using System.Text;

namespace CoffeeBean
{
    /// <summary>
    /// 生成到内嵌包里的"运行时支撑代码"模板。
    ///
    /// **为什么是模板而不是模块里的运行时程序集**：本模块是 Editor-only（不产出 Runtime 程序集），
    /// 而生成的 Getter 要在玩家包里跑 —— 所以运行时逻辑必须以**源码**形式生成到内嵌包里，
    /// 由生成代码所在程序集自行编译。这也意味着：改容器格式要同时改
    /// <see cref="CExcelDataContainer"/>（生成端）和本模板（运行时端），两边算法必须逐字节一致。
    /// </summary>
    internal static class CExcelRuntimeTemplate
    {
        /// <summary>运行时支撑文件名（放在内嵌包的 Runtime/ 下）。</summary>
        public const string RuntimeFileName = "ConfigTableRuntime.cs";

        /// <summary>运行时支撑代码：容器解码 + 数据路径解析 + 全量预加载。</summary>
        public static string RuntimeSource(string ns, string packageName, string keySeed)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by CoffeeBean.Excel. Do not edit.");
            sb.AppendLine("// Runtime support for generated config tables (container .cbcfg).");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using System.IO.Compression;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Networking;");
            sb.AppendLine();
            sb.AppendLine("namespace " + ns);
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>单张配置表的运行时句柄（由各 Getter 自注册）。</summary>");
            sb.AppendLine("    public interface IConfigTable");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>数据文件相对数据根的路径，如 \"Table/Data/Table.cbcfg\"。</summary>");
            sb.AppendLine("        string DataRelativePath { get; }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>把容器字节灌进该表的缓存（由预加载器调用）。</summary>");
            sb.AppendLine("        void Apply(byte[] container);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 配置表运行时：数据路径解析 + 容器解码 + 全量预加载。");
            sb.AppendLine("    /// 数据与代码同处内嵌包 " + packageName + "，**不在 Assets 内**；");
            sb.AppendLine("    /// 打包时由生成模块的 BuildPlayerProcessor 通过 AddAdditionalPathToStreamingAssets 挂进构建产物。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class ConfigTableRuntime");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>内嵌包名（生成时固化）：Editor 下数据在 Packages/<包名>/，Player 下在 StreamingAssets/<包名>/。</summary>");
            sb.AppendLine("        public const string PackageName = \"" + packageName + "\";");
            sb.AppendLine();
            sb.AppendLine("        public const string Magic = \"CBG1\";");
            sb.AppendLine("        public const byte ContainerVersion = 1;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>数据文件扩展名（生成代码里也要用，所以固化在运行时）。</summary>");
            sb.AppendLine("        public const string DataExtension = \"" + CExcelDataContainer.Extension + "\";");
            sb.AppendLine();
            sb.AppendLine("        private const byte FlagCompressed = 1;");
            sb.AppendLine("        private const byte FlagEncrypted = 2;");
            sb.AppendLine("        private const int HeaderSize = 16;");
            sb.AppendLine("        private const string KeySeed = \"" + keySeed + "\";");
            sb.AppendLine();
            sb.AppendLine("        private static readonly List<IConfigTable> Tables = new List<IConfigTable>();");
            sb.AppendLine("        private static bool _preloaded;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>是否已完成一次全量预加载。</summary>");
            sb.AppendLine("        public static bool IsPreloaded { get { return _preloaded; } }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>已注册的表数量（可用于自检生成是否跟上）。</summary>");
            sb.AppendLine("        public static int RegisteredTableCount { get { return Tables.Count; } }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>注册一张表（由生成的 Getter 在 SubsystemRegistration 时自调用）。</summary>");
            sb.AppendLine("        public static void Register(IConfigTable table)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (table != null && !Tables.Contains(table)) Tables.Add(table);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>数据在 StreamingAssets 内、只能异步读（Android 玩家包）。</summary>");
            sb.AppendLine("        public static bool IsStreamingAssetsOnly");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine("#if UNITY_ANDROID && !UNITY_EDITOR");
            sb.AppendLine("                return true;");
            sb.AppendLine("#else");
            sb.AppendLine("                return false;");
            sb.AppendLine("#endif");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>数据根目录的绝对路径。</summary>");
            sb.AppendLine("        public static string DataRoot");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("                // Editor 下直接读内嵌包本体（工程根/Packages/<包名>）——");
            sb.AppendLine("                // AddAdditionalPathToStreamingAssets 只在构建期生效，不会出现在 Assets/StreamingAssets 里。");
            sb.AppendLine("                return Path.GetFullPath(Path.Combine(Application.dataPath, \"..\", \"Packages\", PackageName));");
            sb.AppendLine("#else");
            sb.AppendLine("                return Path.Combine(Application.streamingAssetsPath, PackageName);");
            sb.AppendLine("#endif");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>同步读一个数据文件；Android 玩家包内不可用（改用 PreloadAll）。</summary>");
            sb.AppendLine("        public static byte[] ReadData(string relativePath)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (IsStreamingAssetsOnly)");
            sb.AppendLine("            {");
            sb.AppendLine("                Debug.LogError(\"[ConfigTableRuntime] Android 上配置在 StreamingAssets 内，必须用 PreloadAll() 预加载，不能同步读: \" + relativePath);");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("            string full = Path.Combine(DataRoot, relativePath.Replace('/', Path.DirectorySeparatorChar));");
            sb.AppendLine("            if (!File.Exists(full))");
            sb.AppendLine("            {");
            sb.AppendLine("                Debug.LogError(\"[ConfigTableRuntime] 配置数据缺失: \" + full + \"（是否忘了生成配置表？）\");");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("            return File.ReadAllBytes(full);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>容器解码：解 XOR → 解 Deflate → 校验长度与校验和。失败返回 null 并给出原因。</summary>");
            sb.AppendLine("        public static string Decode(byte[] container, out string error)");
            sb.AppendLine("        {");
            sb.AppendLine("            error = null;");
            sb.AppendLine("            if (container == null || container.Length < HeaderSize) { error = \"容器为空或太短\"; return null; }");
            sb.AppendLine("            if (container[0] != 'C' || container[1] != 'B' || container[2] != 'G' || container[3] != '1')");
            sb.AppendLine("            {");
            sb.AppendLine("                error = \"魔术字不匹配（不是 .cbcfg 容器）\";");
            sb.AppendLine("                return null;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (container[4] != ContainerVersion) { error = \"容器版本不支持: \" + container[4]; return null; }");
            sb.AppendLine();
            sb.AppendLine("            byte flags = container[5];");
            sb.AppendLine("            uint rawLength = ReadUInt32(container, 8);");
            sb.AppendLine("            uint rawChecksum = ReadUInt32(container, 12);");
            sb.AppendLine();
            sb.AppendLine("            var payload = new byte[container.Length - HeaderSize];");
            sb.AppendLine("            Buffer.BlockCopy(container, HeaderSize, payload, 0, payload.Length);");
            sb.AppendLine();
            sb.AppendLine("            if ((flags & FlagEncrypted) != 0) payload = Xor(payload);");
            sb.AppendLine("            if ((flags & FlagCompressed) != 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                try { payload = Inflate(payload); }");
            sb.AppendLine("                catch (Exception e) { error = \"解压失败: \" + e.Message; return null; }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            if (payload.Length != rawLength) { error = \"长度不符: 头部 \" + rawLength + \" / 实际 \" + payload.Length; return null; }");
            sb.AppendLine("            if (Checksum(payload) != rawChecksum) { error = \"校验和不符（数据损坏或被篡改）\"; return null; }");
            sb.AppendLine("            return Encoding.UTF8.GetString(payload);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>全量预加载：把每张表的数据读进来灌好缓存，之后同步 API 直接可用。</summary>");
            sb.AppendLine("        /// <param name=\"onProgress\">(已完成, 总数)，可用于进度条。</param>");
            sb.AppendLine("        /// <param name=\"onError\">某个表失败时回调（相对路径 + 原因）；不中断其余表。</param>");
            sb.AppendLine("        public static IEnumerator PreloadAll(Action<int, int> onProgress = null, Action<string> onError = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            int total = Tables.Count;");
            sb.AppendLine("            if (total == 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                // 注册靠 RuntimeInitializeOnLoadMethod(SubsystemRegistration)：它在**进入 Play Mode / 玩家包启动**时触发，");
            sb.AppendLine("                // Editor 非 Play 状态下不会触发 → 这里别静默空转，直接说清楚（Editor 里请用各 Getter 的同步接口，懒加载照常可用）。");
            sb.AppendLine("                Debug.LogWarning(\"[ConfigTableRuntime] 没有已注册的表，PreloadAll 未做任何事。\" +");
            sb.AppendLine("                                 \"若在 Editor 非 Play 状态下调用，这是预期行为（注册发生在进入 Play Mode 时）；\" +");
            sb.AppendLine("                                 \"直接访问各 Getter 的同步接口即可（懒加载），或在 Play Mode / 玩家包里调用本方法。\");");
            sb.AppendLine("                yield break;");
            sb.AppendLine("            }");
            sb.AppendLine("            // 去重：章节表会被「每章节 Getter + 聚合 Getter」各注册一次，同一个文件只读一遍");
            sb.AppendLine("            var loaded = new Dictionary<string, byte[]>();");
            sb.AppendLine("            for (int i = 0; i < total; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                IConfigTable table = Tables[i];");
            sb.AppendLine("                byte[] bytes;");
            sb.AppendLine("                string transportError = null;");
            sb.AppendLine();
            sb.AppendLine("                if (loaded.TryGetValue(table.DataRelativePath, out bytes))");
            sb.AppendLine("                {");
            sb.AppendLine("                    try { table.Apply(bytes); }");
            sb.AppendLine("                    catch (Exception e) { if (onError != null) onError(table.DataRelativePath + \": \" + e.Message); }");
            sb.AppendLine("                    if (onProgress != null) onProgress(i + 1, total);");
            sb.AppendLine("                    continue;");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                bytes = null;");
            sb.AppendLine("                if (IsStreamingAssetsOnly)");
            sb.AppendLine("                {");
            sb.AppendLine("                    string url = Path.Combine(DataRoot, table.DataRelativePath.Replace('/', Path.DirectorySeparatorChar));");
            sb.AppendLine("                    using (UnityWebRequest request = UnityWebRequest.Get(url))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        yield return request.SendWebRequest();");
            sb.AppendLine("                        if (request.result != UnityWebRequest.Result.Success) transportError = request.error;");
            sb.AppendLine("                        else bytes = request.downloadHandler.data;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    bytes = ReadData(table.DataRelativePath);");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                if (bytes == null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (onError != null) onError(table.DataRelativePath + (string.IsNullOrEmpty(transportError) ? \"\" : \": \" + transportError));");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    loaded[table.DataRelativePath] = bytes;");
            sb.AppendLine("                    try { table.Apply(bytes); }");
            sb.AppendLine("                    catch (Exception e) { if (onError != null) onError(table.DataRelativePath + \": \" + e.Message); }");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                if (onProgress != null) onProgress(i + 1, total);");
            sb.AppendLine("            }");
            sb.AppendLine("            _preloaded = true;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Deflate 解压（与生成端 CExcelDataContainer.Deflate 对称）。</summary>");
            sb.AppendLine("        private static byte[] Inflate(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            using (var input = new MemoryStream(data))");
            sb.AppendLine("            using (var deflate = new DeflateStream(input, CompressionMode.Decompress))");
            sb.AppendLine("            using (var output = new MemoryStream())");
            sb.AppendLine("            {");
            sb.AppendLine("                deflate.CopyTo(output);");
            sb.AppendLine("                return output.ToArray();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>按位异或（与生成端同种子同算法）。</summary>");
            sb.AppendLine("        private static byte[] Xor(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            byte[] result = new byte[data.Length];");
            sb.AppendLine("            uint state = 2166136261;");
            sb.AppendLine("            for (int i = 0; i < data.Length; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                state ^= KeySeed[i % KeySeed.Length];");
            sb.AppendLine("                state *= 16777619;");
            sb.AppendLine("                result[i] = (byte)(data[i] ^ (byte)(state >> 24) ^ (byte)(i & 0x7F));");
            sb.AppendLine("            }");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>FNV-1a 32 位校验（与生成端一致）。</summary>");
            sb.AppendLine("        private static uint Checksum(byte[] data)");
            sb.AppendLine("        {");
            sb.AppendLine("            uint hash = 2166136261;");
            sb.AppendLine("            for (int i = 0; i < data.Length; i++) { hash ^= data[i]; hash *= 16777619; }");
            sb.AppendLine("            return hash;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static uint ReadUInt32(byte[] buffer, int offset)");
            sb.AppendLine("        {");
            sb.AppendLine("            return (uint)(buffer[offset] | (buffer[offset + 1] << 8) | (buffer[offset + 2] << 16) | (buffer[offset + 3] << 24));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>内嵌包的 package.json（生成器产出，幂等：已存在不覆盖）。</summary>
        public static string PackageJson(string packageName, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine("  \"name\": \"" + packageName + "\",");
            sb.AppendLine("  \"version\": \"1.0.0\",");
            sb.AppendLine("  \"displayName\": \"" + ns + " Generated Configs\",");
            sb.AppendLine("  \"description\": \"Auto-generated config table code (CoffeeBean.Excel). Do not edit by hand.\",");
            sb.AppendLine("  \"author\": { \"name\": \"CoffeeBean.Excel\" }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>包根标记文件名：构建钩子靠它发现"哪些包里有配置数据、要挂进 StreamingAssets"。</summary>
        public const string MarkerFileName = "coffeebean.configgen.json";

        /// <summary>包根标记文件内容（幂等覆盖：内容由生成选项决定，过期会导致打包漏挂数据）。</summary>
        public static string MarkerJson(string packageName, string ns)
        {
            var sb = new StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine("  \"generator\": \"CoffeeBean.Excel\",");
            sb.AppendLine("  \"packageName\": \"" + packageName + "\",");
            sb.AppendLine("  \"namespace\": \"" + ns + "\",");
            sb.AppendLine("  \"note\": \"Marks this package as a generated config package. The build hook mounts every <Table>/Data folder into StreamingAssets/<packageName>/. Do not delete.\"");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
